kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: filebeat-stock-prod
  namespace: stock
  labels:
    k8s-app: filebeat-stock-prod
spec:
  selector:
    matchLabels:
      k8s-app: filebeat-stock-prod
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: filebeat-stock-prod
    spec:
      restartPolicy: Always
      serviceAccountName: filebeat-stock-prod
      schedulerName: default-scheduler
      hostNetwork: true
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: 150m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          name: filebeat
          env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch
            - name: ELASTICSEARCH_PORT
              value: '9200'
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: TZ
              value: Europe/Istanbul
          securityContext:
            privileged: true
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /etc/filebeat-stock-prod.yml
              subPath: filebeat-stock-prod.yml
            - name: data
              mountPath: /usr/share/filebeat-stock-prod/data
            - name: varlibdockercontainers
              readOnly: true
              mountPath: /var/lib/docker/containers
            - name: varlogpods
              readOnly: true
              mountPath: /var/log/pods
            - name: varlog
              readOnly: true
              mountPath: /var/log
            - name: filebeat-cert
              readOnly: true
              mountPath: /etc/pki/client/
          terminationMessagePolicy: File
          image: 'docker.elastic.co/beats/filebeat:7.11.1'
          args:
            - '-c'
            - /etc/filebeat-stock-prod.yml
            - '-e'
      serviceAccount: filebeat-stock-prod
      volumes:
        - name: config
          configMap:
            name: filebeat-stock-prod-config
            defaultMode: 416
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
            type: ''
        - name: varlogpods
          hostPath:
            path: /var/log/pods
            type: ''
        - name: varlog
          hostPath:
            path: /var/log
            type: ''
        - name: data
          hostPath:
            path: /var/lib/filebeat-stock-data
            type: DirectoryOrCreate
        - name: filebeat-cert
          secret:
            secretName: filebeat-stock-prod-dockercfg-zg89k
            defaultMode: 416
      dnsPolicy: ClusterFirstWithHostNet
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
